public class MyClass {
    public static Integer getInt1() {
        return 1;
    }
    
    public static Integer getInt2() {
        return 1;
    }
    
    public static Integer getInt3() {
        return 1;
    }
    
    public static Integer getInt4() {
        return 1;
    }
    
    public static Integer getInt5() {
        return 1;
    }
    
    public static Integer getInt6() {
        return 1;
    }
}